// NCERT / CBSE curriculum data for Classes 9-12
// Chapter lists sourced from NCERT textbook tables of contents.

export type Chapter = string;
export type Subject = { name: string; chapters: Chapter[] };
export type ClassData = { label: string; subjects: Subject[] };

export const CURRICULUM: Record<string, ClassData> = {
  "9": {
    label: "Class 9",
    subjects: [
      {
        name: "Mathematics",
        chapters: [
          "Number Systems",
          "Polynomials",
          "Coordinate Geometry",
          "Linear Equations in Two Variables",
          "Introduction to Euclid's Geometry",
          "Lines and Angles",
          "Triangles",
          "Quadrilaterals",
          "Circles",
          "Heron's Formula",
          "Surface Areas and Volumes",
          "Statistics",
        ],
      },
      {
        name: "Science",
        chapters: [
          "Matter in Our Surroundings",
          "Is Matter Around Us Pure",
          "Atoms and Molecules",
          "Structure of the Atom",
          "The Fundamental Unit of Life",
          "Tissues",
          "Motion",
          "Force and Laws of Motion",
          "Gravitation",
          "Work and Energy",
          "Sound",
          "Improvement in Food Resources",
        ],
      },
      {
        name: "Social Science",
        chapters: [
          "The French Revolution",
          "Socialism in Europe and the Russian Revolution",
          "Nazism and the Rise of Hitler",
          "Forest Society and Colonialism",
          "Pastoralists in the Modern World",
          "India — Size and Location",
          "Physical Features of India",
          "Drainage",
          "Climate",
          "Natural Vegetation and Wildlife",
          "Population",
          "What is Democracy? Why Democracy?",
          "Constitutional Design",
          "Electoral Politics",
          "Working of Institutions",
          "Democratic Rights",
          "The Story of Village Palampur",
          "People as Resource",
          "Poverty as a Challenge",
          "Food Security in India",
        ],
      },
      {
        name: "English",
        chapters: [
          "The Fun They Had",
          "The Sound of Music",
          "The Little Girl",
          "A Truly Beautiful Mind",
          "The Snake and the Mirror",
          "My Childhood",
          "Reach for the Top",
          "Kathmandu",
          "If I Were You",
        ],
      },
    ],
  },
  "10": {
    label: "Class 10",
    subjects: [
      {
        name: "Mathematics",
        chapters: [
          "Real Numbers",
          "Polynomials",
          "Pair of Linear Equations in Two Variables",
          "Quadratic Equations",
          "Arithmetic Progressions",
          "Triangles",
          "Coordinate Geometry",
          "Introduction to Trigonometry",
          "Some Applications of Trigonometry",
          "Circles",
          "Areas Related to Circles",
          "Surface Areas and Volumes",
          "Statistics",
          "Probability",
        ],
      },
      {
        name: "Science",
        chapters: [
          "Chemical Reactions and Equations",
          "Acids, Bases and Salts",
          "Metals and Non-Metals",
          "Carbon and Its Compounds",
          "Life Processes",
          "Control and Coordination",
          "How do Organisms Reproduce?",
          "Heredity",
          "Light — Reflection and Refraction",
          "The Human Eye and the Colourful World",
          "Electricity",
          "Magnetic Effects of Electric Current",
          "Our Environment",
        ],
      },
      {
        name: "Social Science",
        chapters: [
          "The Rise of Nationalism in Europe",
          "Nationalism in India",
          "The Making of a Global World",
          "The Age of Industrialisation",
          "Print Culture and the Modern World",
          "Resources and Development",
          "Forest and Wildlife Resources",
          "Water Resources",
          "Agriculture",
          "Minerals and Energy Resources",
          "Manufacturing Industries",
          "Lifelines of National Economy",
          "Power Sharing",
          "Federalism",
          "Gender, Religion and Caste",
          "Political Parties",
          "Outcomes of Democracy",
          "Development",
          "Sectors of the Indian Economy",
          "Money and Credit",
          "Globalisation and the Indian Economy",
          "Consumer Rights",
        ],
      },
      {
        name: "English",
        chapters: [
          "A Letter to God",
          "Nelson Mandela: Long Walk to Freedom",
          "Two Stories about Flying",
          "From the Diary of Anne Frank",
          "Glimpses of India",
          "Mijbil the Otter",
          "Madam Rides the Bus",
          "The Sermon at Benares",
          "The Proposal",
        ],
      },
    ],
  },
  "11": {
    label: "Class 11",
    subjects: [
      {
        name: "Physics",
        chapters: [
          "Units and Measurements",
          "Motion in a Straight Line",
          "Motion in a Plane",
          "Laws of Motion",
          "Work, Energy and Power",
          "System of Particles and Rotational Motion",
          "Gravitation",
          "Mechanical Properties of Solids",
          "Mechanical Properties of Fluids",
          "Thermal Properties of Matter",
          "Thermodynamics",
          "Kinetic Theory",
          "Oscillations",
          "Waves",
        ],
      },
      {
        name: "Chemistry",
        chapters: [
          "Some Basic Concepts of Chemistry",
          "Structure of Atom",
          "Classification of Elements and Periodicity in Properties",
          "Chemical Bonding and Molecular Structure",
          "Thermodynamics",
          "Equilibrium",
          "Redox Reactions",
          "Organic Chemistry — Some Basic Principles and Techniques",
          "Hydrocarbons",
        ],
      },
      {
        name: "Biology",
        chapters: [
          "The Living World",
          "Biological Classification",
          "Plant Kingdom",
          "Animal Kingdom",
          "Morphology of Flowering Plants",
          "Anatomy of Flowering Plants",
          "Structural Organisation in Animals",
          "Cell — The Unit of Life",
          "Biomolecules",
          "Cell Cycle and Cell Division",
          "Photosynthesis in Higher Plants",
          "Respiration in Plants",
          "Plant Growth and Development",
          "Breathing and Exchange of Gases",
          "Body Fluids and Circulation",
          "Excretory Products and Their Elimination",
          "Locomotion and Movement",
          "Neural Control and Coordination",
          "Chemical Coordination and Integration",
        ],
      },
      {
        name: "Mathematics",
        chapters: [
          "Sets",
          "Relations and Functions",
          "Trigonometric Functions",
          "Complex Numbers and Quadratic Equations",
          "Linear Inequalities",
          "Permutations and Combinations",
          "Binomial Theorem",
          "Sequences and Series",
          "Straight Lines",
          "Conic Sections",
          "Introduction to Three Dimensional Geometry",
          "Limits and Derivatives",
          "Statistics",
          "Probability",
        ],
      },
      {
        name: "English",
        chapters: [
          "The Portrait of a Lady",
          "We're Not Afraid to Die… if We Can All Be Together",
          "Discovering Tut: the Saga Continues",
          "Landscape of the Soul",
          "The Ailing Planet",
          "The Browning Version",
          "The Adventure",
          "Silk Road",
        ],
      },
    ],
  },
  "12": {
    label: "Class 12",
    subjects: [
      {
        name: "Physics",
        chapters: [
          "Electric Charges and Fields",
          "Electrostatic Potential and Capacitance",
          "Current Electricity",
          "Moving Charges and Magnetism",
          "Magnetism and Matter",
          "Electromagnetic Induction",
          "Alternating Current",
          "Electromagnetic Waves",
          "Ray Optics and Optical Instruments",
          "Wave Optics",
          "Dual Nature of Radiation and Matter",
          "Atoms",
          "Nuclei",
          "Semiconductor Electronics",
        ],
      },
      {
        name: "Chemistry",
        chapters: [
          "Solutions",
          "Electrochemistry",
          "Chemical Kinetics",
          "The d- and f-Block Elements",
          "Coordination Compounds",
          "Haloalkanes and Haloarenes",
          "Alcohols, Phenols and Ethers",
          "Aldehydes, Ketones and Carboxylic Acids",
          "Amines",
          "Biomolecules",
        ],
      },
      {
        name: "Biology",
        chapters: [
          "Sexual Reproduction in Flowering Plants",
          "Human Reproduction",
          "Reproductive Health",
          "Principles of Inheritance and Variation",
          "Molecular Basis of Inheritance",
          "Evolution",
          "Human Health and Disease",
          "Microbes in Human Welfare",
          "Biotechnology — Principles and Processes",
          "Biotechnology and Its Applications",
          "Organisms and Populations",
          "Ecosystem",
          "Biodiversity and Conservation",
        ],
      },
      {
        name: "Mathematics",
        chapters: [
          "Relations and Functions",
          "Inverse Trigonometric Functions",
          "Matrices",
          "Determinants",
          "Continuity and Differentiability",
          "Application of Derivatives",
          "Integrals",
          "Application of Integrals",
          "Differential Equations",
          "Vector Algebra",
          "Three Dimensional Geometry",
          "Linear Programming",
          "Probability",
        ],
      },
      {
        name: "English",
        chapters: [
          "The Last Lesson",
          "Lost Spring",
          "Deep Water",
          "The Rattrap",
          "Indigo",
          "Poets and Pancakes",
          "The Interview",
          "Going Places",
          "My Mother at Sixty-six",
          "An Elementary School Classroom in a Slum",
          "Keeping Quiet",
          "A Thing of Beauty",
          "Aunt Jennifer's Tigers",
        ],
      },
    ],
  },
};

export const CLASS_KEYS = ["9", "10", "11", "12"] as const;
